= Contributing

Thank you for your interest in contributing to this set of Code Katas !

== Contribution Guide

=== Build policy

The Code Katas in this repository are arranged as independent maven projects that can be orchestrated or built together using the aggregator and **parent pom** pom.xml at the root of the project. The parent pom (located at the root of the project) defines a few properties used throughout (such as the *JUnit version*, and the *Java compiler's source and target* version). In addition, some common build plugins are configured under the `pluginManagement` section of the parent pom.

==== REQUIREMENT
The individual Kata projects should remain independent build targets and should not depend on any other module or kata for a successful build.

=== Kata structure

Irrespective of the contribution style (a full module or enhancement/bug fix to existing module), here are some requirements:

==== General Project Structure

The project layout in the every Code Kata is similar.Here is a tree structure to explain:

[source]
----
|____pom.xml                   <------------------- Project pom, using the java-katas/pom.xml as parent
|____README.md                 <------------------- Well documented README, with links to tests & solutions
|
|____src
| |
| |____test                    <------------------- Kata Tests
| | |____java
| |   |____none
| |     |____cvg
| |       |____<kata package>  <------------------- Name the package that corresponds to the kata.
| |       |____<kata pkg 2>    <------------------- Optional multiple packages if the kata covers more sections
| |
| |____main                    <------------------- Shared content (re-used in both tests and solutions)
| | |____java
| |   |____none
| |     |____cvg
| |
| |____solutions               <------------------- Solutions
| | |____java
| |   |____none
| |     |____cvg
| |       |____<kata package>  <------------------- Name the package that corresponds to the kata.
| |       |____<kata pkg 2>    <------------------- Optional multiple packages if the kata covers more sections

----
==== REQUIREMENT
The Code Kata project structure should comply with the setup of a `test` folder with failing tests, and a `solution` folder with solved working tests.

When contributing to this repository, please first discuss the change you wish to make via issue,
email, or any other method with the owners of this repository before making a change.

== Code of Conduct

In the interest of fostering an open and welcoming environment, we as
contributors and maintainers pledge to making participation in our project, and
our community a harassment-free experience for everyone, regardless of age, body
size, disability, ethnicity, gender identity and expression, level of experience,
nationality, personal appearance, race, religion, or sexual identity and
orientation.

=== Our Standards

Examples of behavior that contributes to creating a positive environment
include:

* Using welcoming and inclusive language
* Being respectful of differing viewpoints and experiences
* Gracefully accepting constructive criticism
* Focusing on what is best for the community
* Showing empathy towards other community members

Examples of unacceptable behavior by participants include:

* The use of sexualized language or imagery and unwelcome sexual attention or
advances
* Trolling, insulting/derogatory comments, and personal or political attacks
* Public or private harassment
* Publishing others' private information, such as a physical or electronic
address, without explicit permission
* Other conduct which could reasonably be considered inappropriate in a
professional setting

=== Our Responsibilities

Project maintainers are responsible for clarifying the standards of acceptable
behavior and are expected to take appropriate and fair corrective action in
response to any instances of unacceptable behavior.

Project maintainers have the right and responsibility to remove, edit, or
reject comments, commits, code, wiki edits, issues, and other contributions
that are not aligned to this Code of Conduct, or to ban temporarily or
permanently any contributor for other behaviors that they deem inappropriate,
threatening, offensive, or harmful.

=== Scope

This Code of Conduct applies both within project spaces and in public spaces
when an individual is representing the project or its community.Examples of
representing a project or community include using an official project e-mail
address, posting via an official social media account, or acting as an appointed
representative at an online or offline event.Representation of a project may be
further defined and clarified by project maintainers.

=== Enforcement

Project maintainers who do not follow or enforce the Code of Conduct in good
faith may face temporary or permanent repercussions as determined by other
members of the project's leadership.

=== Attribution

This Code of Conduct is adapted from the [Contributor Covenant][homepage], version 1.4,
available at [http://contributor-covenant.org/version/1/4][version]

[homepage]: http://contributor-covenant.org
[version]: http://contributor-covenant.org/version/1/4/
